spring.datasource.url: jdbc:h2:file:./camunda-h2-database

server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: update
  
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      platform: h2

camunda:
  bpm:
    enable-java-beans-property-access: true
    deployment-resource-pattern: classpath:/static.bpmn/*.bpmn
    admin-user:
      id: demo
      password: demo
    database:
      schema-update: true



